root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./bin/server"
  # Kill previous process if it did not close
  pre_cmd = ["lsof -i tcp:3000 | awk '$1 == \"COMMAND\" {next} {print $2}' | xargs -I {} kill -9 {}"]
  cmd = "make run ARGS=\"-load-env\""
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin", "db/pg/pg_generated", "node_modules", "static"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "templ"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  rerun = false
  rerun_delay = 700
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
