version: "3.5"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - gochatapp:/var/lib/postgresql/data
  mailer:
    image: maildev/maildev:latest
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  gochatapp:
