// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package pg

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Project struct {
	ID          int
	PublicID    uuid.UUID
	Name        string
	Description string
	OwnerID     int
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type ProjectAssignment struct {
	ProjectID      int
	UserID         int
	ProjectOwnerID int
}

type ProjectInvitation struct {
	ProjectID  int
	Email      string
	SentAt     time.Time
	ExpiresAt  time.Time
	AcceptedAt sql.NullTime
}

type Todo struct {
	ID          int
	PublicID    uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
	ProjectID   int
}

type TodoAssignment struct {
	TodoID int
	UserID int
}

type User struct {
	ID        int
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
